//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: AutoPilot.cpp
//  Source: AutoPilot.idl
//  Generated: Mon Jan  9 16:42:13 2017
//  OpenSplice V5.5.1OSS
//  
//******************************************************************

#include "AutoPilot.h"




