//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: AutoPilot.h
//  Source: AutoPilot.idl
//  Generated: Mon Jan  9 16:42:13 2017
//  OpenSplice V5.5.1OSS
//  
//******************************************************************
#ifndef _AUTOPILOT_H_
#define _AUTOPILOT_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"

namespace AutoPilot
{
   struct AutoPilotData;

   struct AutoPilotData
   {
      DDS::Long ID;
      DDS::Double ThrottleCommand;
      DDS::Double ElevatorCommand;
      DDS::Double AileronCommand;
      DDS::Double RudderCommand;
      DDS::Double LeftBrakeCommand;
      DDS::Double RightBrakeCommand;
      DDS::Double FlapCommand;
      DDS::Boolean EngineStartSwitch;
      DDS::Double WindSpeedCommand;
      DDS::Double WindDirectionCommand;
   };

   typedef DDS_DCPSStruct_var < AutoPilotData> AutoPilotData_var;
   typedef AutoPilotData&AutoPilotData_out;
}




#endif 
