//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: FDM.h
//  Source: FDM.idl
//  Generated: Sat Feb 18 13:31:06 2017
//  OpenSplice V5.5.1OSS
//  
//******************************************************************
#ifndef _FDM_H_
#define _FDM_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"

namespace FDM
{
   struct fdmdata;

   struct fdmdata
   {
      DDS::Long ID;
      DDS::Double Velocity_Kts;
      DDS::Double MachNumber;
      DDS::Double GValue;
      DDS::Double SideSlip;
      DDS::Double Roll_deg;
      DDS::Double Pitch_deg;
      DDS::Double AtmosphereTemperature;
      DDS::Double Heading_deg;
      DDS::Double Altitude_ft;
      DDS::Double VerticleVelocity_fpm;
      DDS::Double Latitude;
      DDS::Double Longitude;
      DDS::Double AltitudeAboveSeaLevel_ft;
      DDS::Double SimTime;
      DDS::Double AngleOFAttack;
      DDS::Double TrueAirSpeed;
      DDS::Double GroundAirSpeed;
      DDS::Double thetadot;
      DDS::Double phidot;
      DDS::Double psidot;
      DDS::Double WindSpeed;
      DDS::Double WindDirection;
      DDS::Boolean GeneratorStatus;
      DDS::Boolean GeneratorIndicatorLight;
      DDS::Double ACBusVoltage;
      DDS::Boolean ACBusIndicatorLight;
      DDS::Double DCBusVoltage;
      DDS::Boolean DCBusIndicatorLight;
      DDS::Double BatteryVoltage;
   };

   typedef DDS_DCPSStruct_var < fdmdata> fdmdata_var;
   typedef fdmdata&fdmdata_out;
}




#endif 
