//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ImageGeneration.cpp
//  Source: ImageGeneration.idl
//  Generated: Tue Feb 28 15:04:54 2017
//  OpenSplice V5.5.1OSS
//  
//******************************************************************

#include "ImageGeneration.h"




