//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: ImageGeneration.h
//  Source: ImageGeneration.idl
//  Generated: Tue Feb 28 15:04:54 2017
//  OpenSplice V5.5.1OSS
//  
//******************************************************************
#ifndef _IMAGEGENERATION_H_
#define _IMAGEGENERATION_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"

namespace ImageGeneration
{
   struct ImageGenerationData;

   struct ImageGenerationData
   {
      DDS::Long ID;
      DDS::Double Roll_deg;
      DDS::Double Pitch_deg;
      DDS::Double Heading_deg;
      DDS::Double Altitude_ft;
      DDS::Double Latitude;
      DDS::Double Longitude;
      DDS::Double AltitudeAboveSeaLevel_ft;
      DDS::Double SimTime;
   };

   typedef DDS_DCPSStruct_var < ImageGenerationData> ImageGenerationData_var;
   typedef ImageGenerationData&ImageGenerationData_out;
}




#endif 
