//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: QTControl.cpp
//  Source: QTControl.idl
//  Generated: Fri Dec  2 14:16:53 2016
//  OpenSplice V5.5.1OSS
//  
//******************************************************************

#include "QTControl.h"




