//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: QTTactEnvironment.h
//  Source: QTTactEnvironment.idl
//  Generated: Wed Nov 11 09:15:21 2015
//  OpenSplice V5.5.1OSS
//  
//******************************************************************
#ifndef _QTTACTENVIRONMENT_H_
#define _QTTACTENVIRONMENT_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"

namespace QTTacticalEnvironment
{
   struct QTTacticalEnvironmentData;

   struct QTTacticalEnvironmentData
   {
      typedef DDS::Boolean _CreatAircraft_array_slice;
      typedef DDS::Boolean _CreatAircraft_array[5];
      typedef _CreatAircraft_array _CreatAircraft_array_out;
      static _CreatAircraft_array_slice * _CreatAircraft_array_alloc ();
      static void _CreatAircraft_array_free (_CreatAircraft_array_slice *);
      static void _CreatAircraft_array_copy (_CreatAircraft_array_slice* to, const _CreatAircraft_array_slice* from);
      static _CreatAircraft_array_slice *_CreatAircraft_array_dup (const _CreatAircraft_array_slice* from);

      struct _CreatAircraft_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _CreatAircraft_array, _CreatAircraft_array_slice, struct _CreatAircraft_array_uniq_> _CreatAircraft_array_var;
      typedef DDS_DCPS_Array_forany< _CreatAircraft_array, _CreatAircraft_array_slice, struct _CreatAircraft_array_uniq_> _CreatAircraft_array_forany;
      typedef DDS::String_mgr _TEAircraftName_array_slice;
      typedef DDS::String_mgr _TEAircraftName_array[5];
      static _TEAircraftName_array_slice * _TEAircraftName_array_alloc ();
      static void _TEAircraftName_array_free (_TEAircraftName_array_slice *);
      static void _TEAircraftName_array_copy (_TEAircraftName_array_slice* to, const _TEAircraftName_array_slice* from);
      static _TEAircraftName_array_slice *_TEAircraftName_array_dup (const _TEAircraftName_array_slice* from);

      struct _TEAircraftName_array_uniq_ {};
      typedef DDS_DCPS_VArray_var< _TEAircraftName_array, _TEAircraftName_array_slice, struct _TEAircraftName_array_uniq_> _TEAircraftName_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftName_array, _TEAircraftName_array_slice, struct _TEAircraftName_array_uniq_> _TEAircraftName_array_forany;
      typedef DDS_DCPS_VLArray_out< _TEAircraftName_array, _TEAircraftName_array_slice, _TEAircraftName_array_var, _TEAircraftName_array_uniq_> _TEAircraftName_array_out;
      typedef DDS::Double _TEAircraftVelocity_array_slice;
      typedef DDS::Double _TEAircraftVelocity_array[5];
      typedef _TEAircraftVelocity_array _TEAircraftVelocity_array_out;
      static _TEAircraftVelocity_array_slice * _TEAircraftVelocity_array_alloc ();
      static void _TEAircraftVelocity_array_free (_TEAircraftVelocity_array_slice *);
      static void _TEAircraftVelocity_array_copy (_TEAircraftVelocity_array_slice* to, const _TEAircraftVelocity_array_slice* from);
      static _TEAircraftVelocity_array_slice *_TEAircraftVelocity_array_dup (const _TEAircraftVelocity_array_slice* from);

      struct _TEAircraftVelocity_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftVelocity_array, _TEAircraftVelocity_array_slice, struct _TEAircraftVelocity_array_uniq_> _TEAircraftVelocity_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftVelocity_array, _TEAircraftVelocity_array_slice, struct _TEAircraftVelocity_array_uniq_> _TEAircraftVelocity_array_forany;
      typedef DDS::Double _TEAircraftDesiredTargetHeading_array_slice;
      typedef DDS::Double _TEAircraftDesiredTargetHeading_array[5];
      typedef _TEAircraftDesiredTargetHeading_array _TEAircraftDesiredTargetHeading_array_out;
      static _TEAircraftDesiredTargetHeading_array_slice * _TEAircraftDesiredTargetHeading_array_alloc ();
      static void _TEAircraftDesiredTargetHeading_array_free (_TEAircraftDesiredTargetHeading_array_slice *);
      static void _TEAircraftDesiredTargetHeading_array_copy (_TEAircraftDesiredTargetHeading_array_slice* to, const _TEAircraftDesiredTargetHeading_array_slice* from);
      static _TEAircraftDesiredTargetHeading_array_slice *_TEAircraftDesiredTargetHeading_array_dup (const _TEAircraftDesiredTargetHeading_array_slice* from);

      struct _TEAircraftDesiredTargetHeading_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftDesiredTargetHeading_array, _TEAircraftDesiredTargetHeading_array_slice, struct _TEAircraftDesiredTargetHeading_array_uniq_> _TEAircraftDesiredTargetHeading_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftDesiredTargetHeading_array, _TEAircraftDesiredTargetHeading_array_slice, struct _TEAircraftDesiredTargetHeading_array_uniq_> _TEAircraftDesiredTargetHeading_array_forany;
      typedef DDS::Long _TEAircraftTotalNumberOfPoints_array_slice;
      typedef DDS::Long _TEAircraftTotalNumberOfPoints_array[5];
      typedef _TEAircraftTotalNumberOfPoints_array _TEAircraftTotalNumberOfPoints_array_out;
      static _TEAircraftTotalNumberOfPoints_array_slice * _TEAircraftTotalNumberOfPoints_array_alloc ();
      static void _TEAircraftTotalNumberOfPoints_array_free (_TEAircraftTotalNumberOfPoints_array_slice *);
      static void _TEAircraftTotalNumberOfPoints_array_copy (_TEAircraftTotalNumberOfPoints_array_slice* to, const _TEAircraftTotalNumberOfPoints_array_slice* from);
      static _TEAircraftTotalNumberOfPoints_array_slice *_TEAircraftTotalNumberOfPoints_array_dup (const _TEAircraftTotalNumberOfPoints_array_slice* from);

      struct _TEAircraftTotalNumberOfPoints_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftTotalNumberOfPoints_array, _TEAircraftTotalNumberOfPoints_array_slice, struct _TEAircraftTotalNumberOfPoints_array_uniq_> _TEAircraftTotalNumberOfPoints_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftTotalNumberOfPoints_array, _TEAircraftTotalNumberOfPoints_array_slice, struct _TEAircraftTotalNumberOfPoints_array_uniq_> _TEAircraftTotalNumberOfPoints_array_forany;
      typedef DDS::Double _TEAircraftRateOfClimb_array_slice;
      typedef DDS::Double _TEAircraftRateOfClimb_array[5];
      typedef _TEAircraftRateOfClimb_array _TEAircraftRateOfClimb_array_out;
      static _TEAircraftRateOfClimb_array_slice * _TEAircraftRateOfClimb_array_alloc ();
      static void _TEAircraftRateOfClimb_array_free (_TEAircraftRateOfClimb_array_slice *);
      static void _TEAircraftRateOfClimb_array_copy (_TEAircraftRateOfClimb_array_slice* to, const _TEAircraftRateOfClimb_array_slice* from);
      static _TEAircraftRateOfClimb_array_slice *_TEAircraftRateOfClimb_array_dup (const _TEAircraftRateOfClimb_array_slice* from);

      struct _TEAircraftRateOfClimb_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftRateOfClimb_array, _TEAircraftRateOfClimb_array_slice, struct _TEAircraftRateOfClimb_array_uniq_> _TEAircraftRateOfClimb_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftRateOfClimb_array, _TEAircraftRateOfClimb_array_slice, struct _TEAircraftRateOfClimb_array_uniq_> _TEAircraftRateOfClimb_array_forany;
      typedef DDS::Double _TEAircraftRateOFTurn_array_slice;
      typedef DDS::Double _TEAircraftRateOFTurn_array[5];
      typedef _TEAircraftRateOFTurn_array _TEAircraftRateOFTurn_array_out;
      static _TEAircraftRateOFTurn_array_slice * _TEAircraftRateOFTurn_array_alloc ();
      static void _TEAircraftRateOFTurn_array_free (_TEAircraftRateOFTurn_array_slice *);
      static void _TEAircraftRateOFTurn_array_copy (_TEAircraftRateOFTurn_array_slice* to, const _TEAircraftRateOFTurn_array_slice* from);
      static _TEAircraftRateOFTurn_array_slice *_TEAircraftRateOFTurn_array_dup (const _TEAircraftRateOFTurn_array_slice* from);

      struct _TEAircraftRateOFTurn_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftRateOFTurn_array, _TEAircraftRateOFTurn_array_slice, struct _TEAircraftRateOFTurn_array_uniq_> _TEAircraftRateOFTurn_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftRateOFTurn_array, _TEAircraftRateOFTurn_array_slice, struct _TEAircraftRateOFTurn_array_uniq_> _TEAircraftRateOFTurn_array_forany;
      typedef DDS::Double _TEAircraftPathLatitude_array_slice[4];
      typedef DDS::Double _TEAircraftPathLatitude_array[5][4];
      typedef _TEAircraftPathLatitude_array _TEAircraftPathLatitude_array_out;
      static _TEAircraftPathLatitude_array_slice * _TEAircraftPathLatitude_array_alloc ();
      static void _TEAircraftPathLatitude_array_free (_TEAircraftPathLatitude_array_slice *);
      static void _TEAircraftPathLatitude_array_copy (_TEAircraftPathLatitude_array_slice* to, const _TEAircraftPathLatitude_array_slice* from);
      static _TEAircraftPathLatitude_array_slice *_TEAircraftPathLatitude_array_dup (const _TEAircraftPathLatitude_array_slice* from);

      struct _TEAircraftPathLatitude_array_uniq_ {};
      typedef DDS_DCPS_MArray_var< _TEAircraftPathLatitude_array, _TEAircraftPathLatitude_array_slice, struct _TEAircraftPathLatitude_array_uniq_> _TEAircraftPathLatitude_array_var;
      typedef DDS_DCPS_MArray_forany< _TEAircraftPathLatitude_array, _TEAircraftPathLatitude_array_slice, struct _TEAircraftPathLatitude_array_uniq_> _TEAircraftPathLatitude_array_forany;
      typedef DDS::Double _TEAircraftPathLongitude_array_slice[4];
      typedef DDS::Double _TEAircraftPathLongitude_array[5][4];
      typedef _TEAircraftPathLongitude_array _TEAircraftPathLongitude_array_out;
      static _TEAircraftPathLongitude_array_slice * _TEAircraftPathLongitude_array_alloc ();
      static void _TEAircraftPathLongitude_array_free (_TEAircraftPathLongitude_array_slice *);
      static void _TEAircraftPathLongitude_array_copy (_TEAircraftPathLongitude_array_slice* to, const _TEAircraftPathLongitude_array_slice* from);
      static _TEAircraftPathLongitude_array_slice *_TEAircraftPathLongitude_array_dup (const _TEAircraftPathLongitude_array_slice* from);

      struct _TEAircraftPathLongitude_array_uniq_ {};
      typedef DDS_DCPS_MArray_var< _TEAircraftPathLongitude_array, _TEAircraftPathLongitude_array_slice, struct _TEAircraftPathLongitude_array_uniq_> _TEAircraftPathLongitude_array_var;
      typedef DDS_DCPS_MArray_forany< _TEAircraftPathLongitude_array, _TEAircraftPathLongitude_array_slice, struct _TEAircraftPathLongitude_array_uniq_> _TEAircraftPathLongitude_array_forany;
      typedef DDS::Double _TEAircraftPathAltitude_array_slice[4];
      typedef DDS::Double _TEAircraftPathAltitude_array[5][4];
      typedef _TEAircraftPathAltitude_array _TEAircraftPathAltitude_array_out;
      static _TEAircraftPathAltitude_array_slice * _TEAircraftPathAltitude_array_alloc ();
      static void _TEAircraftPathAltitude_array_free (_TEAircraftPathAltitude_array_slice *);
      static void _TEAircraftPathAltitude_array_copy (_TEAircraftPathAltitude_array_slice* to, const _TEAircraftPathAltitude_array_slice* from);
      static _TEAircraftPathAltitude_array_slice *_TEAircraftPathAltitude_array_dup (const _TEAircraftPathAltitude_array_slice* from);

      struct _TEAircraftPathAltitude_array_uniq_ {};
      typedef DDS_DCPS_MArray_var< _TEAircraftPathAltitude_array, _TEAircraftPathAltitude_array_slice, struct _TEAircraftPathAltitude_array_uniq_> _TEAircraftPathAltitude_array_var;
      typedef DDS_DCPS_MArray_forany< _TEAircraftPathAltitude_array, _TEAircraftPathAltitude_array_slice, struct _TEAircraftPathAltitude_array_uniq_> _TEAircraftPathAltitude_array_forany;
      typedef DDS::Double _TEAircraftPathHeading_array_slice[4];
      typedef DDS::Double _TEAircraftPathHeading_array[5][4];
      typedef _TEAircraftPathHeading_array _TEAircraftPathHeading_array_out;
      static _TEAircraftPathHeading_array_slice * _TEAircraftPathHeading_array_alloc ();
      static void _TEAircraftPathHeading_array_free (_TEAircraftPathHeading_array_slice *);
      static void _TEAircraftPathHeading_array_copy (_TEAircraftPathHeading_array_slice* to, const _TEAircraftPathHeading_array_slice* from);
      static _TEAircraftPathHeading_array_slice *_TEAircraftPathHeading_array_dup (const _TEAircraftPathHeading_array_slice* from);

      struct _TEAircraftPathHeading_array_uniq_ {};
      typedef DDS_DCPS_MArray_var< _TEAircraftPathHeading_array, _TEAircraftPathHeading_array_slice, struct _TEAircraftPathHeading_array_uniq_> _TEAircraftPathHeading_array_var;
      typedef DDS_DCPS_MArray_forany< _TEAircraftPathHeading_array, _TEAircraftPathHeading_array_slice, struct _TEAircraftPathHeading_array_uniq_> _TEAircraftPathHeading_array_forany;
      DDS::Long ID;
      _CreatAircraft_array CreatAircraft;
      _TEAircraftName_array TEAircraftName;
      _TEAircraftVelocity_array TEAircraftVelocity;
      _TEAircraftDesiredTargetHeading_array TEAircraftDesiredTargetHeading;
      _TEAircraftTotalNumberOfPoints_array TEAircraftTotalNumberOfPoints;
      _TEAircraftRateOfClimb_array TEAircraftRateOfClimb;
      _TEAircraftRateOFTurn_array TEAircraftRateOFTurn;
      _TEAircraftPathLatitude_array TEAircraftPathLatitude;
      _TEAircraftPathLongitude_array TEAircraftPathLongitude;
      _TEAircraftPathAltitude_array TEAircraftPathAltitude;
      _TEAircraftPathHeading_array TEAircraftPathHeading;
   };

   typedef DDS_DCPSStruct_var < QTTacticalEnvironmentData> QTTacticalEnvironmentData_var;
   typedef DDS_DCPSStruct_out < QTTacticalEnvironmentData> QTTacticalEnvironmentData_out;
}
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice *ptr);




#endif 
