//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: QTTactEnvironment.cpp
//  Source: QTTactEnvironment.idl
//  Generated: Wed Nov 11 09:15:21 2015
//  OpenSplice V5.5.1OSS
//  
//******************************************************************

#include "QTTactEnvironment.h"


#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPS_MArray_var< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_uniq_>;
template class DDS_DCPS_MArray_forany< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_uniq_>;
#endif

template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_uniq_>::alloc ()
{
   return QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_alloc ();
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice* from)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_copy (to, from);
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice *ptr)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_free (ptr);
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_alloc ()
{
   DDS::Double * ret = (DDS::Double*) new DDS::Double [20];
   return (_TEAircraftPathHeading_array_slice *) ret;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_free (_TEAircraftPathHeading_array_slice * s)
{
   delete [] s;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_copy
(
   _TEAircraftPathHeading_array_slice * to,
   const _TEAircraftPathHeading_array_slice * from
)
{
   DDS::Double* sv = (DDS::Double*) from;
   DDS::Double* tv = (DDS::Double*) to;
   for (DDS::ULong i = 0; i < 20; i++) tv[i] = sv[i];
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_dup
   (const _TEAircraftPathHeading_array_slice * from)
{
   _TEAircraftPathHeading_array_slice * to = _TEAircraftPathHeading_array_alloc ();
   _TEAircraftPathHeading_array_copy (to, from);
   return to;
}


#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPS_MArray_var< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_uniq_>;
template class DDS_DCPS_MArray_forany< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_uniq_>;
#endif

template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_uniq_>::alloc ()
{
   return QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_alloc ();
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice* from)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_copy (to, from);
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice *ptr)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_free (ptr);
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_alloc ()
{
   DDS::Double * ret = (DDS::Double*) new DDS::Double [20];
   return (_TEAircraftPathAltitude_array_slice *) ret;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_free (_TEAircraftPathAltitude_array_slice * s)
{
   delete [] s;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_copy
(
   _TEAircraftPathAltitude_array_slice * to,
   const _TEAircraftPathAltitude_array_slice * from
)
{
   DDS::Double* sv = (DDS::Double*) from;
   DDS::Double* tv = (DDS::Double*) to;
   for (DDS::ULong i = 0; i < 20; i++) tv[i] = sv[i];
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_dup
   (const _TEAircraftPathAltitude_array_slice * from)
{
   _TEAircraftPathAltitude_array_slice * to = _TEAircraftPathAltitude_array_alloc ();
   _TEAircraftPathAltitude_array_copy (to, from);
   return to;
}


#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPS_MArray_var< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_uniq_>;
template class DDS_DCPS_MArray_forany< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_uniq_>;
#endif

template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_uniq_>::alloc ()
{
   return QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_alloc ();
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice* from)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_copy (to, from);
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice *ptr)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_free (ptr);
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_alloc ()
{
   DDS::Double * ret = (DDS::Double*) new DDS::Double [20];
   return (_TEAircraftPathLongitude_array_slice *) ret;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_free (_TEAircraftPathLongitude_array_slice * s)
{
   delete [] s;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_copy
(
   _TEAircraftPathLongitude_array_slice * to,
   const _TEAircraftPathLongitude_array_slice * from
)
{
   DDS::Double* sv = (DDS::Double*) from;
   DDS::Double* tv = (DDS::Double*) to;
   for (DDS::ULong i = 0; i < 20; i++) tv[i] = sv[i];
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_dup
   (const _TEAircraftPathLongitude_array_slice * from)
{
   _TEAircraftPathLongitude_array_slice * to = _TEAircraftPathLongitude_array_alloc ();
   _TEAircraftPathLongitude_array_copy (to, from);
   return to;
}


#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPS_MArray_var< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_uniq_>;
template class DDS_DCPS_MArray_forany< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_uniq_>;
#endif

template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_uniq_>::alloc ()
{
   return QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_alloc ();
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice* from)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_copy (to, from);
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice *ptr)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_free (ptr);
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_alloc ()
{
   DDS::Double * ret = (DDS::Double*) new DDS::Double [20];
   return (_TEAircraftPathLatitude_array_slice *) ret;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_free (_TEAircraftPathLatitude_array_slice * s)
{
   delete [] s;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_copy
(
   _TEAircraftPathLatitude_array_slice * to,
   const _TEAircraftPathLatitude_array_slice * from
)
{
   DDS::Double* sv = (DDS::Double*) from;
   DDS::Double* tv = (DDS::Double*) to;
   for (DDS::ULong i = 0; i < 20; i++) tv[i] = sv[i];
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_dup
   (const _TEAircraftPathLatitude_array_slice * from)
{
   _TEAircraftPathLatitude_array_slice * to = _TEAircraftPathLatitude_array_alloc ();
   _TEAircraftPathLatitude_array_copy (to, from);
   return to;
}


#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPS_FArray_var< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_uniq_>;
template class DDS_DCPS_Array_forany< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_uniq_>;
#endif

template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_uniq_>::alloc ()
{
   return QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_alloc ();
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice* from)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_copy (to, from);
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice *ptr)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_free (ptr);
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_alloc ()
{
   DDS::Double * ret = (DDS::Double*) new DDS::Double [5];
   return (_TEAircraftRateOFTurn_array_slice *) ret;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_free (_TEAircraftRateOFTurn_array_slice * s)
{
   delete [] s;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_copy
(
   _TEAircraftRateOFTurn_array_slice * to,
   const _TEAircraftRateOFTurn_array_slice * from
)
{
   DDS::Double* sv = (DDS::Double*) from;
   DDS::Double* tv = (DDS::Double*) to;
   for (DDS::ULong i = 0; i < 5; i++) tv[i] = sv[i];
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_dup
   (const _TEAircraftRateOFTurn_array_slice * from)
{
   _TEAircraftRateOFTurn_array_slice * to = _TEAircraftRateOFTurn_array_alloc ();
   _TEAircraftRateOFTurn_array_copy (to, from);
   return to;
}


#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPS_FArray_var< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_uniq_>;
template class DDS_DCPS_Array_forany< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_uniq_>;
#endif

template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_uniq_>::alloc ()
{
   return QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_alloc ();
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice* from)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_copy (to, from);
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice *ptr)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_free (ptr);
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_alloc ()
{
   DDS::Double * ret = (DDS::Double*) new DDS::Double [5];
   return (_TEAircraftRateOfClimb_array_slice *) ret;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_free (_TEAircraftRateOfClimb_array_slice * s)
{
   delete [] s;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_copy
(
   _TEAircraftRateOfClimb_array_slice * to,
   const _TEAircraftRateOfClimb_array_slice * from
)
{
   DDS::Double* sv = (DDS::Double*) from;
   DDS::Double* tv = (DDS::Double*) to;
   for (DDS::ULong i = 0; i < 5; i++) tv[i] = sv[i];
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_dup
   (const _TEAircraftRateOfClimb_array_slice * from)
{
   _TEAircraftRateOfClimb_array_slice * to = _TEAircraftRateOfClimb_array_alloc ();
   _TEAircraftRateOfClimb_array_copy (to, from);
   return to;
}


#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPS_FArray_var< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_uniq_>;
template class DDS_DCPS_Array_forany< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_uniq_>;
#endif

template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_uniq_>::alloc ()
{
   return QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_alloc ();
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice* from)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_copy (to, from);
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice *ptr)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_free (ptr);
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_alloc ()
{
   DDS::Long * ret = (DDS::Long*) new DDS::Long [5];
   return (_TEAircraftTotalNumberOfPoints_array_slice *) ret;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_free (_TEAircraftTotalNumberOfPoints_array_slice * s)
{
   delete [] s;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_copy
(
   _TEAircraftTotalNumberOfPoints_array_slice * to,
   const _TEAircraftTotalNumberOfPoints_array_slice * from
)
{
   DDS::Long* sv = (DDS::Long*) from;
   DDS::Long* tv = (DDS::Long*) to;
   for (DDS::ULong i = 0; i < 5; i++) tv[i] = sv[i];
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_dup
   (const _TEAircraftTotalNumberOfPoints_array_slice * from)
{
   _TEAircraftTotalNumberOfPoints_array_slice * to = _TEAircraftTotalNumberOfPoints_array_alloc ();
   _TEAircraftTotalNumberOfPoints_array_copy (to, from);
   return to;
}


#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPS_FArray_var< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_uniq_>;
template class DDS_DCPS_Array_forany< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_uniq_>;
#endif

template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_uniq_>::alloc ()
{
   return QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_alloc ();
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice* from)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_copy (to, from);
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice *ptr)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_free (ptr);
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_alloc ()
{
   DDS::Double * ret = (DDS::Double*) new DDS::Double [5];
   return (_TEAircraftDesiredTargetHeading_array_slice *) ret;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_free (_TEAircraftDesiredTargetHeading_array_slice * s)
{
   delete [] s;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_copy
(
   _TEAircraftDesiredTargetHeading_array_slice * to,
   const _TEAircraftDesiredTargetHeading_array_slice * from
)
{
   DDS::Double* sv = (DDS::Double*) from;
   DDS::Double* tv = (DDS::Double*) to;
   for (DDS::ULong i = 0; i < 5; i++) tv[i] = sv[i];
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_dup
   (const _TEAircraftDesiredTargetHeading_array_slice * from)
{
   _TEAircraftDesiredTargetHeading_array_slice * to = _TEAircraftDesiredTargetHeading_array_alloc ();
   _TEAircraftDesiredTargetHeading_array_copy (to, from);
   return to;
}


#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPS_FArray_var< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_uniq_>;
template class DDS_DCPS_Array_forany< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_uniq_>;
#endif

template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_uniq_>::alloc ()
{
   return QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_alloc ();
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice* from)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_copy (to, from);
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice *ptr)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_free (ptr);
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_alloc ()
{
   DDS::Double * ret = (DDS::Double*) new DDS::Double [5];
   return (_TEAircraftVelocity_array_slice *) ret;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_free (_TEAircraftVelocity_array_slice * s)
{
   delete [] s;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_copy
(
   _TEAircraftVelocity_array_slice * to,
   const _TEAircraftVelocity_array_slice * from
)
{
   DDS::Double* sv = (DDS::Double*) from;
   DDS::Double* tv = (DDS::Double*) to;
   for (DDS::ULong i = 0; i < 5; i++) tv[i] = sv[i];
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_dup
   (const _TEAircraftVelocity_array_slice * from)
{
   _TEAircraftVelocity_array_slice * to = _TEAircraftVelocity_array_alloc ();
   _TEAircraftVelocity_array_copy (to, from);
   return to;
}


#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPS_VArray_var< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_uniq_>;
template class DDS_DCPS_Array_forany< QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_uniq_>;
template class DDS_DCPS_VLArray_out < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_var, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_uniq_>;
#endif

template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_uniq_>::alloc ()
{
   return QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_alloc ();
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice* from)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_copy (to, from);
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice *ptr)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_free (ptr);
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_alloc ()
{
   DDS::String_mgr * ret = (DDS::String_mgr*) new DDS::String_mgr [5];
   for (DDS::ULong i = 0; i < 5; i++)
   {
      ret[i] = (DDS::String) 0;
   }
   return (_TEAircraftName_array_slice *) ret;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_free (_TEAircraftName_array_slice * s)
{
   if (s)
   {
      DDS::String_mgr * base = (DDS::String_mgr*) s;
      for (DDS::ULong i = 0; i < 5; i++)
      {
         base[i] = (DDS::String) 0;
      }
   }
   delete [] s;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_copy
(
   _TEAircraftName_array_slice * to,
   const _TEAircraftName_array_slice * from
)
{
   DDS::String_mgr* sv = (DDS::String_mgr*) from;
   DDS::String_mgr* tv = (DDS::String_mgr*) to;
   for (DDS::ULong i = 0; i < 5; i++) tv[i] = DDS::string_dup (sv[i]);
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_dup
   (const _TEAircraftName_array_slice * from)
{
   _TEAircraftName_array_slice * to = _TEAircraftName_array_alloc ();
   _TEAircraftName_array_copy (to, from);
   return to;
}


#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPS_FArray_var< QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_uniq_>;
template class DDS_DCPS_Array_forany< QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice, struct QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_uniq_>;
#endif

template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_uniq_>::alloc ()
{
   return QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_alloc ();
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice* from)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_copy (to, from);
}

template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice *ptr)
{
   QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_free (ptr);
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_alloc ()
{
   DDS::Boolean * ret = (DDS::Boolean*) new DDS::Boolean [5];
   return (_CreatAircraft_array_slice *) ret;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_free (_CreatAircraft_array_slice * s)
{
   delete [] s;
}

void QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_copy
(
   _CreatAircraft_array_slice * to,
   const _CreatAircraft_array_slice * from
)
{
   DDS::Boolean* sv = (DDS::Boolean*) from;
   DDS::Boolean* tv = (DDS::Boolean*) to;
   for (DDS::ULong i = 0; i < 5; i++) tv[i] = sv[i];
}

QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice * QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_dup
   (const _CreatAircraft_array_slice * from)
{
   _CreatAircraft_array_slice * to = _CreatAircraft_array_alloc ();
   _CreatAircraft_array_copy (to, from);
   return to;
}




