//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: QTTactEnvironmentDcps.h
//  Source: QTTactEnvironmentData/QTTactEnvironmentDcps.idl
//  Generated: Wed Nov 11 09:15:21 2015
//  OpenSplice V5.5.1OSS
//  
//******************************************************************
#ifndef _QTTACTENVIRONMENTDCPS_H_
#define _QTTACTENVIRONMENTDCPS_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "dds_dcps_interfaces.h"
#include "QTTactEnvironment.h"
#include "dds_builtinTopics.h"
#include "dds_dcps_builtintopics.h"

namespace QTTacticalEnvironment
{
   struct QTTacticalEnvironmentData;

   class QTTacticalEnvironmentDataTypeSupportInterface;

   typedef QTTacticalEnvironmentDataTypeSupportInterface * QTTacticalEnvironmentDataTypeSupportInterface_ptr;
   typedef DDS_DCPSInterface_var < QTTacticalEnvironmentDataTypeSupportInterface> QTTacticalEnvironmentDataTypeSupportInterface_var;
   typedef DDS_DCPSInterface_out < QTTacticalEnvironmentDataTypeSupportInterface> QTTacticalEnvironmentDataTypeSupportInterface_out;


   class QTTacticalEnvironmentDataDataWriter;

   typedef QTTacticalEnvironmentDataDataWriter * QTTacticalEnvironmentDataDataWriter_ptr;
   typedef DDS_DCPSInterface_var < QTTacticalEnvironmentDataDataWriter> QTTacticalEnvironmentDataDataWriter_var;
   typedef DDS_DCPSInterface_out < QTTacticalEnvironmentDataDataWriter> QTTacticalEnvironmentDataDataWriter_out;


   class QTTacticalEnvironmentDataDataReader;

   typedef QTTacticalEnvironmentDataDataReader * QTTacticalEnvironmentDataDataReader_ptr;
   typedef DDS_DCPSInterface_var < QTTacticalEnvironmentDataDataReader> QTTacticalEnvironmentDataDataReader_var;
   typedef DDS_DCPSInterface_out < QTTacticalEnvironmentDataDataReader> QTTacticalEnvironmentDataDataReader_out;


   class QTTacticalEnvironmentDataDataReaderView;

   typedef QTTacticalEnvironmentDataDataReaderView * QTTacticalEnvironmentDataDataReaderView_ptr;
   typedef DDS_DCPSInterface_var < QTTacticalEnvironmentDataDataReaderView> QTTacticalEnvironmentDataDataReaderView_var;
   typedef DDS_DCPSInterface_out < QTTacticalEnvironmentDataDataReaderView> QTTacticalEnvironmentDataDataReaderView_out;

   struct QTTacticalEnvironmentDataSeq_uniq_ {};
   typedef DDS_DCPSUVLSeq < QTTacticalEnvironmentData, struct QTTacticalEnvironmentDataSeq_uniq_> QTTacticalEnvironmentDataSeq;
   typedef DDS_DCPSSequence_var < QTTacticalEnvironmentDataSeq> QTTacticalEnvironmentDataSeq_var;
   typedef DDS_DCPSSequence_out < QTTacticalEnvironmentDataSeq> QTTacticalEnvironmentDataSeq_out;
   class QTTacticalEnvironmentDataTypeSupportInterface
   :
      virtual public DDS::TypeSupport
   { 
   public:
      typedef QTTacticalEnvironmentDataTypeSupportInterface_ptr _ptr_type;
      typedef QTTacticalEnvironmentDataTypeSupportInterface_var _var_type;

      static QTTacticalEnvironmentDataTypeSupportInterface_ptr _duplicate (QTTacticalEnvironmentDataTypeSupportInterface_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static QTTacticalEnvironmentDataTypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
      static QTTacticalEnvironmentDataTypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static QTTacticalEnvironmentDataTypeSupportInterface_ptr _nil () { return 0; }
      static const char * _local_id;
      QTTacticalEnvironmentDataTypeSupportInterface_ptr _this () { return this; }


   protected:
      QTTacticalEnvironmentDataTypeSupportInterface () {};
      ~QTTacticalEnvironmentDataTypeSupportInterface () {};
   private:
      QTTacticalEnvironmentDataTypeSupportInterface (const QTTacticalEnvironmentDataTypeSupportInterface &);
      QTTacticalEnvironmentDataTypeSupportInterface & operator = (const QTTacticalEnvironmentDataTypeSupportInterface &);
   };

   class QTTacticalEnvironmentDataDataWriter
   :
      virtual public DDS::DataWriter
   { 
   public:
      typedef QTTacticalEnvironmentDataDataWriter_ptr _ptr_type;
      typedef QTTacticalEnvironmentDataDataWriter_var _var_type;

      static QTTacticalEnvironmentDataDataWriter_ptr _duplicate (QTTacticalEnvironmentDataDataWriter_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static QTTacticalEnvironmentDataDataWriter_ptr _narrow (DDS::Object_ptr obj);
      static QTTacticalEnvironmentDataDataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static QTTacticalEnvironmentDataDataWriter_ptr _nil () { return 0; }
      static const char * _local_id;
      QTTacticalEnvironmentDataDataWriter_ptr _this () { return this; }

      virtual DDS::InstanceHandle_t register_instance (const QTTacticalEnvironmentData& instance_data) = 0;
      virtual DDS::InstanceHandle_t register_instance_w_timestamp (const QTTacticalEnvironmentData& instance_data, const DDS::Time_t& source_timestamp) = 0;
      virtual DDS::ReturnCode_t unregister_instance (const QTTacticalEnvironmentData& instance_data, DDS::InstanceHandle_t handle) = 0;
      virtual DDS::ReturnCode_t unregister_instance_w_timestamp (const QTTacticalEnvironmentData& instance_data, DDS::InstanceHandle_t handle, const DDS::Time_t& source_timestamp) = 0;
      virtual DDS::ReturnCode_t write (const QTTacticalEnvironmentData& instance_data, DDS::InstanceHandle_t handle) = 0;
      virtual DDS::ReturnCode_t write_w_timestamp (const QTTacticalEnvironmentData& instance_data, DDS::InstanceHandle_t handle, const DDS::Time_t& source_timestamp) = 0;
      virtual DDS::ReturnCode_t dispose (const QTTacticalEnvironmentData& instance_data, DDS::InstanceHandle_t handle) = 0;
      virtual DDS::ReturnCode_t dispose_w_timestamp (const QTTacticalEnvironmentData& instance_data, DDS::InstanceHandle_t handle, const DDS::Time_t& source_timestamp) = 0;
      virtual DDS::ReturnCode_t writedispose (const QTTacticalEnvironmentData& instance_data, DDS::InstanceHandle_t handle) = 0;
      virtual DDS::ReturnCode_t writedispose_w_timestamp (const QTTacticalEnvironmentData& instance_data, DDS::InstanceHandle_t handle, const DDS::Time_t& source_timestamp) = 0;
      virtual DDS::ReturnCode_t get_key_value (QTTacticalEnvironmentData& key_holder, DDS::InstanceHandle_t handle) = 0;
      virtual DDS::InstanceHandle_t lookup_instance (const QTTacticalEnvironmentData& instance_data) = 0;

   protected:
      QTTacticalEnvironmentDataDataWriter () {};
      ~QTTacticalEnvironmentDataDataWriter () {};
   private:
      QTTacticalEnvironmentDataDataWriter (const QTTacticalEnvironmentDataDataWriter &);
      QTTacticalEnvironmentDataDataWriter & operator = (const QTTacticalEnvironmentDataDataWriter &);
   };

   class QTTacticalEnvironmentDataDataReader
   :
      virtual public DDS::DataReader
   { 
   public:
      typedef QTTacticalEnvironmentDataDataReader_ptr _ptr_type;
      typedef QTTacticalEnvironmentDataDataReader_var _var_type;

      static QTTacticalEnvironmentDataDataReader_ptr _duplicate (QTTacticalEnvironmentDataDataReader_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static QTTacticalEnvironmentDataDataReader_ptr _narrow (DDS::Object_ptr obj);
      static QTTacticalEnvironmentDataDataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static QTTacticalEnvironmentDataDataReader_ptr _nil () { return 0; }
      static const char * _local_id;
      QTTacticalEnvironmentDataDataReader_ptr _this () { return this; }

      virtual DDS::ReturnCode_t read (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::SampleStateMask sample_states, DDS::ViewStateMask view_states, DDS::InstanceStateMask instance_states) = 0;
      virtual DDS::ReturnCode_t take (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::SampleStateMask sample_states, DDS::ViewStateMask view_states, DDS::InstanceStateMask instance_states) = 0;
      virtual DDS::ReturnCode_t read_w_condition (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
      virtual DDS::ReturnCode_t take_w_condition (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
      virtual DDS::ReturnCode_t read_next_sample (QTTacticalEnvironmentData& received_data, DDS::SampleInfo& sample_info) = 0;
      virtual DDS::ReturnCode_t take_next_sample (QTTacticalEnvironmentData& received_data, DDS::SampleInfo& sample_info) = 0;
      virtual DDS::ReturnCode_t read_instance (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::InstanceHandle_t a_handle, DDS::SampleStateMask sample_states, DDS::ViewStateMask view_states, DDS::InstanceStateMask instance_states) = 0;
      virtual DDS::ReturnCode_t take_instance (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::InstanceHandle_t a_handle, DDS::SampleStateMask sample_states, DDS::ViewStateMask view_states, DDS::InstanceStateMask instance_states) = 0;
      virtual DDS::ReturnCode_t read_next_instance (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::InstanceHandle_t a_handle, DDS::SampleStateMask sample_states, DDS::ViewStateMask view_states, DDS::InstanceStateMask instance_states) = 0;
      virtual DDS::ReturnCode_t take_next_instance (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::InstanceHandle_t a_handle, DDS::SampleStateMask sample_states, DDS::ViewStateMask view_states, DDS::InstanceStateMask instance_states) = 0;
      virtual DDS::ReturnCode_t read_next_instance_w_condition (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::InstanceHandle_t a_handle, DDS::ReadCondition_ptr a_condition) = 0;
      virtual DDS::ReturnCode_t take_next_instance_w_condition (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::InstanceHandle_t a_handle, DDS::ReadCondition_ptr a_condition) = 0;
      virtual DDS::ReturnCode_t return_loan (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
      virtual DDS::ReturnCode_t get_key_value (QTTacticalEnvironmentData& key_holder, DDS::InstanceHandle_t handle) = 0;
      virtual DDS::InstanceHandle_t lookup_instance (const QTTacticalEnvironmentData& instance) = 0;

   protected:
      QTTacticalEnvironmentDataDataReader () {};
      ~QTTacticalEnvironmentDataDataReader () {};
   private:
      QTTacticalEnvironmentDataDataReader (const QTTacticalEnvironmentDataDataReader &);
      QTTacticalEnvironmentDataDataReader & operator = (const QTTacticalEnvironmentDataDataReader &);
   };

   class QTTacticalEnvironmentDataDataReaderView
   :
      virtual public DDS::DataReaderView
   { 
   public:
      typedef QTTacticalEnvironmentDataDataReaderView_ptr _ptr_type;
      typedef QTTacticalEnvironmentDataDataReaderView_var _var_type;

      static QTTacticalEnvironmentDataDataReaderView_ptr _duplicate (QTTacticalEnvironmentDataDataReaderView_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static QTTacticalEnvironmentDataDataReaderView_ptr _narrow (DDS::Object_ptr obj);
      static QTTacticalEnvironmentDataDataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static QTTacticalEnvironmentDataDataReaderView_ptr _nil () { return 0; }
      static const char * _local_id;
      QTTacticalEnvironmentDataDataReaderView_ptr _this () { return this; }

      virtual DDS::ReturnCode_t read (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::SampleStateMask sample_states, DDS::ViewStateMask view_states, DDS::InstanceStateMask instance_states) = 0;
      virtual DDS::ReturnCode_t take (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::SampleStateMask sample_states, DDS::ViewStateMask view_states, DDS::InstanceStateMask instance_states) = 0;
      virtual DDS::ReturnCode_t read_w_condition (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
      virtual DDS::ReturnCode_t take_w_condition (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::ReadCondition_ptr a_condition) = 0;
      virtual DDS::ReturnCode_t read_next_sample (QTTacticalEnvironmentData& received_data, DDS::SampleInfo& sample_info) = 0;
      virtual DDS::ReturnCode_t take_next_sample (QTTacticalEnvironmentData& received_data, DDS::SampleInfo& sample_info) = 0;
      virtual DDS::ReturnCode_t read_instance (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::InstanceHandle_t a_handle, DDS::SampleStateMask sample_states, DDS::ViewStateMask view_states, DDS::InstanceStateMask instance_states) = 0;
      virtual DDS::ReturnCode_t take_instance (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::InstanceHandle_t a_handle, DDS::SampleStateMask sample_states, DDS::ViewStateMask view_states, DDS::InstanceStateMask instance_states) = 0;
      virtual DDS::ReturnCode_t read_next_instance (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::InstanceHandle_t a_handle, DDS::SampleStateMask sample_states, DDS::ViewStateMask view_states, DDS::InstanceStateMask instance_states) = 0;
      virtual DDS::ReturnCode_t take_next_instance (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::InstanceHandle_t a_handle, DDS::SampleStateMask sample_states, DDS::ViewStateMask view_states, DDS::InstanceStateMask instance_states) = 0;
      virtual DDS::ReturnCode_t read_next_instance_w_condition (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::InstanceHandle_t a_handle, DDS::ReadCondition_ptr a_condition) = 0;
      virtual DDS::ReturnCode_t take_next_instance_w_condition (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq, DDS::Long max_samples, DDS::InstanceHandle_t a_handle, DDS::ReadCondition_ptr a_condition) = 0;
      virtual DDS::ReturnCode_t return_loan (QTTacticalEnvironmentDataSeq& received_data, DDS::SampleInfoSeq& info_seq) = 0;
      virtual DDS::ReturnCode_t get_key_value (QTTacticalEnvironmentData& key_holder, DDS::InstanceHandle_t handle) = 0;
      virtual DDS::InstanceHandle_t lookup_instance (const QTTacticalEnvironmentData& instance) = 0;

   protected:
      QTTacticalEnvironmentDataDataReaderView () {};
      ~QTTacticalEnvironmentDataDataReaderView () {};
   private:
      QTTacticalEnvironmentDataDataReaderView (const QTTacticalEnvironmentDataDataReaderView &);
      QTTacticalEnvironmentDataDataReaderView & operator = (const QTTacticalEnvironmentDataDataReaderView &);
   };

}
template <>
DDS::BuiltinTopicKey_t_slice* DDS_DCPS_ArrayHelper < DDS::BuiltinTopicKey_t, DDS::BuiltinTopicKey_t_slice, DDS::BuiltinTopicKey_t_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < DDS::BuiltinTopicKey_t, DDS::BuiltinTopicKey_t_slice, DDS::BuiltinTopicKey_t_uniq_>::copy (DDS::BuiltinTopicKey_t_slice *to, const DDS::BuiltinTopicKey_t_slice* from);
template <>
void DDS_DCPS_ArrayHelper < DDS::BuiltinTopicKey_t, DDS::BuiltinTopicKey_t_slice, DDS::BuiltinTopicKey_t_uniq_>::free (DDS::BuiltinTopicKey_t_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_CreatAircraft_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftName_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftVelocity_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftDesiredTargetHeading_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftTotalNumberOfPoints_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOfClimb_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftRateOFTurn_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLatitude_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathLongitude_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathAltitude_array_slice *ptr);
template <>
QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice* DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_uniq_>::copy (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice *to, const QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice, QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_uniq_>::free (QTTacticalEnvironment::QTTacticalEnvironmentData::_TEAircraftPathHeading_array_slice *ptr);




#endif 
