//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: QTTactEnvironmentDcps.cpp
//  Source: QTTactEnvironmentData/QTTactEnvironmentDcps.idl
//  Generated: Wed Nov 11 09:15:21 2015
//  OpenSplice V5.5.1OSS
//  
//******************************************************************

#include "QTTactEnvironmentDcps.h"

#if DDS_USE_EXPLICIT_TEMPLATES
template class DDS_DCPSUVLSeq < QTTacticalEnvironment::QTTacticalEnvironmentData, struct QTTacticalEnvironmentDataSeq_uniq_>;
#endif

const char * QTTacticalEnvironment::QTTacticalEnvironmentDataTypeSupportInterface::_local_id = "IDL:QTTacticalEnvironment/QTTacticalEnvironmentDataTypeSupportInterface:1.0";

QTTacticalEnvironment::QTTacticalEnvironmentDataTypeSupportInterface_ptr QTTacticalEnvironment::QTTacticalEnvironmentDataTypeSupportInterface::_duplicate (QTTacticalEnvironment::QTTacticalEnvironmentDataTypeSupportInterface_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean QTTacticalEnvironment::QTTacticalEnvironmentDataTypeSupportInterface::_local_is_a (const char * _id)
{
   if (strcmp (_id, QTTacticalEnvironment::QTTacticalEnvironmentDataTypeSupportInterface::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::TypeSupport NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

QTTacticalEnvironment::QTTacticalEnvironmentDataTypeSupportInterface_ptr QTTacticalEnvironment::QTTacticalEnvironmentDataTypeSupportInterface::_narrow (DDS::Object_ptr p)
{
   QTTacticalEnvironment::QTTacticalEnvironmentDataTypeSupportInterface_ptr result = NULL;
   if (p && p->_is_a (QTTacticalEnvironment::QTTacticalEnvironmentDataTypeSupportInterface::_local_id))
   {
      result = dynamic_cast < QTTacticalEnvironment::QTTacticalEnvironmentDataTypeSupportInterface_ptr> (p);
      result->m_count++;
   }
   return result;
}

QTTacticalEnvironment::QTTacticalEnvironmentDataTypeSupportInterface_ptr QTTacticalEnvironment::QTTacticalEnvironmentDataTypeSupportInterface::_unchecked_narrow (DDS::Object_ptr p)
{
   QTTacticalEnvironment::QTTacticalEnvironmentDataTypeSupportInterface_ptr result;
   result = dynamic_cast < QTTacticalEnvironment::QTTacticalEnvironmentDataTypeSupportInterface_ptr> (p);
   result->m_count++;
   return result;
}

const char * QTTacticalEnvironment::QTTacticalEnvironmentDataDataWriter::_local_id = "IDL:QTTacticalEnvironment/QTTacticalEnvironmentDataDataWriter:1.0";

QTTacticalEnvironment::QTTacticalEnvironmentDataDataWriter_ptr QTTacticalEnvironment::QTTacticalEnvironmentDataDataWriter::_duplicate (QTTacticalEnvironment::QTTacticalEnvironmentDataDataWriter_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean QTTacticalEnvironment::QTTacticalEnvironmentDataDataWriter::_local_is_a (const char * _id)
{
   if (strcmp (_id, QTTacticalEnvironment::QTTacticalEnvironmentDataDataWriter::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataWriter NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

QTTacticalEnvironment::QTTacticalEnvironmentDataDataWriter_ptr QTTacticalEnvironment::QTTacticalEnvironmentDataDataWriter::_narrow (DDS::Object_ptr p)
{
   QTTacticalEnvironment::QTTacticalEnvironmentDataDataWriter_ptr result = NULL;
   if (p && p->_is_a (QTTacticalEnvironment::QTTacticalEnvironmentDataDataWriter::_local_id))
   {
      result = dynamic_cast < QTTacticalEnvironment::QTTacticalEnvironmentDataDataWriter_ptr> (p);
      result->m_count++;
   }
   return result;
}

QTTacticalEnvironment::QTTacticalEnvironmentDataDataWriter_ptr QTTacticalEnvironment::QTTacticalEnvironmentDataDataWriter::_unchecked_narrow (DDS::Object_ptr p)
{
   QTTacticalEnvironment::QTTacticalEnvironmentDataDataWriter_ptr result;
   result = dynamic_cast < QTTacticalEnvironment::QTTacticalEnvironmentDataDataWriter_ptr> (p);
   result->m_count++;
   return result;
}

const char * QTTacticalEnvironment::QTTacticalEnvironmentDataDataReader::_local_id = "IDL:QTTacticalEnvironment/QTTacticalEnvironmentDataDataReader:1.0";

QTTacticalEnvironment::QTTacticalEnvironmentDataDataReader_ptr QTTacticalEnvironment::QTTacticalEnvironmentDataDataReader::_duplicate (QTTacticalEnvironment::QTTacticalEnvironmentDataDataReader_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean QTTacticalEnvironment::QTTacticalEnvironmentDataDataReader::_local_is_a (const char * _id)
{
   if (strcmp (_id, QTTacticalEnvironment::QTTacticalEnvironmentDataDataReader::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataReader NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

QTTacticalEnvironment::QTTacticalEnvironmentDataDataReader_ptr QTTacticalEnvironment::QTTacticalEnvironmentDataDataReader::_narrow (DDS::Object_ptr p)
{
   QTTacticalEnvironment::QTTacticalEnvironmentDataDataReader_ptr result = NULL;
   if (p && p->_is_a (QTTacticalEnvironment::QTTacticalEnvironmentDataDataReader::_local_id))
   {
      result = dynamic_cast < QTTacticalEnvironment::QTTacticalEnvironmentDataDataReader_ptr> (p);
      result->m_count++;
   }
   return result;
}

QTTacticalEnvironment::QTTacticalEnvironmentDataDataReader_ptr QTTacticalEnvironment::QTTacticalEnvironmentDataDataReader::_unchecked_narrow (DDS::Object_ptr p)
{
   QTTacticalEnvironment::QTTacticalEnvironmentDataDataReader_ptr result;
   result = dynamic_cast < QTTacticalEnvironment::QTTacticalEnvironmentDataDataReader_ptr> (p);
   result->m_count++;
   return result;
}

const char * QTTacticalEnvironment::QTTacticalEnvironmentDataDataReaderView::_local_id = "IDL:QTTacticalEnvironment/QTTacticalEnvironmentDataDataReaderView:1.0";

QTTacticalEnvironment::QTTacticalEnvironmentDataDataReaderView_ptr QTTacticalEnvironment::QTTacticalEnvironmentDataDataReaderView::_duplicate (QTTacticalEnvironment::QTTacticalEnvironmentDataDataReaderView_ptr p)
{
   if (p) p->m_count++;
   return p;
}

DDS::Boolean QTTacticalEnvironment::QTTacticalEnvironmentDataDataReaderView::_local_is_a (const char * _id)
{
   if (strcmp (_id, QTTacticalEnvironment::QTTacticalEnvironmentDataDataReaderView::_local_id) == 0)
   {
      return true;
   }

   typedef DDS::DataReaderView NestedBase_1;

   if (NestedBase_1::_local_is_a (_id))
   {
      return true;
   }

   return false;
}

QTTacticalEnvironment::QTTacticalEnvironmentDataDataReaderView_ptr QTTacticalEnvironment::QTTacticalEnvironmentDataDataReaderView::_narrow (DDS::Object_ptr p)
{
   QTTacticalEnvironment::QTTacticalEnvironmentDataDataReaderView_ptr result = NULL;
   if (p && p->_is_a (QTTacticalEnvironment::QTTacticalEnvironmentDataDataReaderView::_local_id))
   {
      result = dynamic_cast < QTTacticalEnvironment::QTTacticalEnvironmentDataDataReaderView_ptr> (p);
      result->m_count++;
   }
   return result;
}

QTTacticalEnvironment::QTTacticalEnvironmentDataDataReaderView_ptr QTTacticalEnvironment::QTTacticalEnvironmentDataDataReaderView::_unchecked_narrow (DDS::Object_ptr p)
{
   QTTacticalEnvironment::QTTacticalEnvironmentDataDataReaderView_ptr result;
   result = dynamic_cast < QTTacticalEnvironment::QTTacticalEnvironmentDataDataReaderView_ptr> (p);
   result->m_count++;
   return result;
}



