//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: TacticalAircrafts.h
//  Source: TacticalAircrafts.idl
//  Generated: Wed Nov 11 09:15:35 2015
//  OpenSplice V5.5.1OSS
//  
//******************************************************************
#ifndef _TACTICALAIRCRAFTS_H_
#define _TACTICALAIRCRAFTS_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"

namespace TacticalAircrafts
{
   struct TacticalAircraftsData;

   struct TacticalAircraftsData
   {
      typedef DDS::Boolean _TEAircraftExists_array_slice;
      typedef DDS::Boolean _TEAircraftExists_array[5];
      typedef _TEAircraftExists_array _TEAircraftExists_array_out;
      static _TEAircraftExists_array_slice * _TEAircraftExists_array_alloc ();
      static void _TEAircraftExists_array_free (_TEAircraftExists_array_slice *);
      static void _TEAircraftExists_array_copy (_TEAircraftExists_array_slice* to, const _TEAircraftExists_array_slice* from);
      static _TEAircraftExists_array_slice *_TEAircraftExists_array_dup (const _TEAircraftExists_array_slice* from);

      struct _TEAircraftExists_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftExists_array, _TEAircraftExists_array_slice, struct _TEAircraftExists_array_uniq_> _TEAircraftExists_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftExists_array, _TEAircraftExists_array_slice, struct _TEAircraftExists_array_uniq_> _TEAircraftExists_array_forany;
      typedef DDS::String_mgr _TEAircraftName_array_slice;
      typedef DDS::String_mgr _TEAircraftName_array[5];
      static _TEAircraftName_array_slice * _TEAircraftName_array_alloc ();
      static void _TEAircraftName_array_free (_TEAircraftName_array_slice *);
      static void _TEAircraftName_array_copy (_TEAircraftName_array_slice* to, const _TEAircraftName_array_slice* from);
      static _TEAircraftName_array_slice *_TEAircraftName_array_dup (const _TEAircraftName_array_slice* from);

      struct _TEAircraftName_array_uniq_ {};
      typedef DDS_DCPS_VArray_var< _TEAircraftName_array, _TEAircraftName_array_slice, struct _TEAircraftName_array_uniq_> _TEAircraftName_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftName_array, _TEAircraftName_array_slice, struct _TEAircraftName_array_uniq_> _TEAircraftName_array_forany;
      typedef DDS_DCPS_VLArray_out< _TEAircraftName_array, _TEAircraftName_array_slice, _TEAircraftName_array_var, _TEAircraftName_array_uniq_> _TEAircraftName_array_out;
      typedef DDS::Double _TEAircraftVelocity_array_slice;
      typedef DDS::Double _TEAircraftVelocity_array[5];
      typedef _TEAircraftVelocity_array _TEAircraftVelocity_array_out;
      static _TEAircraftVelocity_array_slice * _TEAircraftVelocity_array_alloc ();
      static void _TEAircraftVelocity_array_free (_TEAircraftVelocity_array_slice *);
      static void _TEAircraftVelocity_array_copy (_TEAircraftVelocity_array_slice* to, const _TEAircraftVelocity_array_slice* from);
      static _TEAircraftVelocity_array_slice *_TEAircraftVelocity_array_dup (const _TEAircraftVelocity_array_slice* from);

      struct _TEAircraftVelocity_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftVelocity_array, _TEAircraftVelocity_array_slice, struct _TEAircraftVelocity_array_uniq_> _TEAircraftVelocity_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftVelocity_array, _TEAircraftVelocity_array_slice, struct _TEAircraftVelocity_array_uniq_> _TEAircraftVelocity_array_forany;
      typedef DDS::Double _TEAircraftLatitude_array_slice;
      typedef DDS::Double _TEAircraftLatitude_array[5];
      typedef _TEAircraftLatitude_array _TEAircraftLatitude_array_out;
      static _TEAircraftLatitude_array_slice * _TEAircraftLatitude_array_alloc ();
      static void _TEAircraftLatitude_array_free (_TEAircraftLatitude_array_slice *);
      static void _TEAircraftLatitude_array_copy (_TEAircraftLatitude_array_slice* to, const _TEAircraftLatitude_array_slice* from);
      static _TEAircraftLatitude_array_slice *_TEAircraftLatitude_array_dup (const _TEAircraftLatitude_array_slice* from);

      struct _TEAircraftLatitude_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftLatitude_array, _TEAircraftLatitude_array_slice, struct _TEAircraftLatitude_array_uniq_> _TEAircraftLatitude_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftLatitude_array, _TEAircraftLatitude_array_slice, struct _TEAircraftLatitude_array_uniq_> _TEAircraftLatitude_array_forany;
      typedef DDS::Double _TEAircraftLongitude_array_slice;
      typedef DDS::Double _TEAircraftLongitude_array[5];
      typedef _TEAircraftLongitude_array _TEAircraftLongitude_array_out;
      static _TEAircraftLongitude_array_slice * _TEAircraftLongitude_array_alloc ();
      static void _TEAircraftLongitude_array_free (_TEAircraftLongitude_array_slice *);
      static void _TEAircraftLongitude_array_copy (_TEAircraftLongitude_array_slice* to, const _TEAircraftLongitude_array_slice* from);
      static _TEAircraftLongitude_array_slice *_TEAircraftLongitude_array_dup (const _TEAircraftLongitude_array_slice* from);

      struct _TEAircraftLongitude_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftLongitude_array, _TEAircraftLongitude_array_slice, struct _TEAircraftLongitude_array_uniq_> _TEAircraftLongitude_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftLongitude_array, _TEAircraftLongitude_array_slice, struct _TEAircraftLongitude_array_uniq_> _TEAircraftLongitude_array_forany;
      typedef DDS::Double _TEAircraftAltitude_array_slice;
      typedef DDS::Double _TEAircraftAltitude_array[5];
      typedef _TEAircraftAltitude_array _TEAircraftAltitude_array_out;
      static _TEAircraftAltitude_array_slice * _TEAircraftAltitude_array_alloc ();
      static void _TEAircraftAltitude_array_free (_TEAircraftAltitude_array_slice *);
      static void _TEAircraftAltitude_array_copy (_TEAircraftAltitude_array_slice* to, const _TEAircraftAltitude_array_slice* from);
      static _TEAircraftAltitude_array_slice *_TEAircraftAltitude_array_dup (const _TEAircraftAltitude_array_slice* from);

      struct _TEAircraftAltitude_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftAltitude_array, _TEAircraftAltitude_array_slice, struct _TEAircraftAltitude_array_uniq_> _TEAircraftAltitude_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftAltitude_array, _TEAircraftAltitude_array_slice, struct _TEAircraftAltitude_array_uniq_> _TEAircraftAltitude_array_forany;
      typedef DDS::Double _TEAircraftHeading_array_slice;
      typedef DDS::Double _TEAircraftHeading_array[5];
      typedef _TEAircraftHeading_array _TEAircraftHeading_array_out;
      static _TEAircraftHeading_array_slice * _TEAircraftHeading_array_alloc ();
      static void _TEAircraftHeading_array_free (_TEAircraftHeading_array_slice *);
      static void _TEAircraftHeading_array_copy (_TEAircraftHeading_array_slice* to, const _TEAircraftHeading_array_slice* from);
      static _TEAircraftHeading_array_slice *_TEAircraftHeading_array_dup (const _TEAircraftHeading_array_slice* from);

      struct _TEAircraftHeading_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftHeading_array, _TEAircraftHeading_array_slice, struct _TEAircraftHeading_array_uniq_> _TEAircraftHeading_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftHeading_array, _TEAircraftHeading_array_slice, struct _TEAircraftHeading_array_uniq_> _TEAircraftHeading_array_forany;
      typedef DDS::Double _TEAircraftPitchAngle_array_slice;
      typedef DDS::Double _TEAircraftPitchAngle_array[5];
      typedef _TEAircraftPitchAngle_array _TEAircraftPitchAngle_array_out;
      static _TEAircraftPitchAngle_array_slice * _TEAircraftPitchAngle_array_alloc ();
      static void _TEAircraftPitchAngle_array_free (_TEAircraftPitchAngle_array_slice *);
      static void _TEAircraftPitchAngle_array_copy (_TEAircraftPitchAngle_array_slice* to, const _TEAircraftPitchAngle_array_slice* from);
      static _TEAircraftPitchAngle_array_slice *_TEAircraftPitchAngle_array_dup (const _TEAircraftPitchAngle_array_slice* from);

      struct _TEAircraftPitchAngle_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftPitchAngle_array, _TEAircraftPitchAngle_array_slice, struct _TEAircraftPitchAngle_array_uniq_> _TEAircraftPitchAngle_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftPitchAngle_array, _TEAircraftPitchAngle_array_slice, struct _TEAircraftPitchAngle_array_uniq_> _TEAircraftPitchAngle_array_forany;
      typedef DDS::Double _TEAircraftRollAngle_array_slice;
      typedef DDS::Double _TEAircraftRollAngle_array[5];
      typedef _TEAircraftRollAngle_array _TEAircraftRollAngle_array_out;
      static _TEAircraftRollAngle_array_slice * _TEAircraftRollAngle_array_alloc ();
      static void _TEAircraftRollAngle_array_free (_TEAircraftRollAngle_array_slice *);
      static void _TEAircraftRollAngle_array_copy (_TEAircraftRollAngle_array_slice* to, const _TEAircraftRollAngle_array_slice* from);
      static _TEAircraftRollAngle_array_slice *_TEAircraftRollAngle_array_dup (const _TEAircraftRollAngle_array_slice* from);

      struct _TEAircraftRollAngle_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftRollAngle_array, _TEAircraftRollAngle_array_slice, struct _TEAircraftRollAngle_array_uniq_> _TEAircraftRollAngle_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftRollAngle_array, _TEAircraftRollAngle_array_slice, struct _TEAircraftRollAngle_array_uniq_> _TEAircraftRollAngle_array_forany;
      typedef DDS::Double _TEAircraftRateOfClimb_array_slice;
      typedef DDS::Double _TEAircraftRateOfClimb_array[5];
      typedef _TEAircraftRateOfClimb_array _TEAircraftRateOfClimb_array_out;
      static _TEAircraftRateOfClimb_array_slice * _TEAircraftRateOfClimb_array_alloc ();
      static void _TEAircraftRateOfClimb_array_free (_TEAircraftRateOfClimb_array_slice *);
      static void _TEAircraftRateOfClimb_array_copy (_TEAircraftRateOfClimb_array_slice* to, const _TEAircraftRateOfClimb_array_slice* from);
      static _TEAircraftRateOfClimb_array_slice *_TEAircraftRateOfClimb_array_dup (const _TEAircraftRateOfClimb_array_slice* from);

      struct _TEAircraftRateOfClimb_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftRateOfClimb_array, _TEAircraftRateOfClimb_array_slice, struct _TEAircraftRateOfClimb_array_uniq_> _TEAircraftRateOfClimb_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftRateOfClimb_array, _TEAircraftRateOfClimb_array_slice, struct _TEAircraftRateOfClimb_array_uniq_> _TEAircraftRateOfClimb_array_forany;
      typedef DDS::Boolean _TEAircraftOnCollissionCourse_array_slice;
      typedef DDS::Boolean _TEAircraftOnCollissionCourse_array[5];
      typedef _TEAircraftOnCollissionCourse_array _TEAircraftOnCollissionCourse_array_out;
      static _TEAircraftOnCollissionCourse_array_slice * _TEAircraftOnCollissionCourse_array_alloc ();
      static void _TEAircraftOnCollissionCourse_array_free (_TEAircraftOnCollissionCourse_array_slice *);
      static void _TEAircraftOnCollissionCourse_array_copy (_TEAircraftOnCollissionCourse_array_slice* to, const _TEAircraftOnCollissionCourse_array_slice* from);
      static _TEAircraftOnCollissionCourse_array_slice *_TEAircraftOnCollissionCourse_array_dup (const _TEAircraftOnCollissionCourse_array_slice* from);

      struct _TEAircraftOnCollissionCourse_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftOnCollissionCourse_array, _TEAircraftOnCollissionCourse_array_slice, struct _TEAircraftOnCollissionCourse_array_uniq_> _TEAircraftOnCollissionCourse_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftOnCollissionCourse_array, _TEAircraftOnCollissionCourse_array_slice, struct _TEAircraftOnCollissionCourse_array_uniq_> _TEAircraftOnCollissionCourse_array_forany;
      typedef DDS::Double _TEAircraftTimeToCollision_array_slice;
      typedef DDS::Double _TEAircraftTimeToCollision_array[5];
      typedef _TEAircraftTimeToCollision_array _TEAircraftTimeToCollision_array_out;
      static _TEAircraftTimeToCollision_array_slice * _TEAircraftTimeToCollision_array_alloc ();
      static void _TEAircraftTimeToCollision_array_free (_TEAircraftTimeToCollision_array_slice *);
      static void _TEAircraftTimeToCollision_array_copy (_TEAircraftTimeToCollision_array_slice* to, const _TEAircraftTimeToCollision_array_slice* from);
      static _TEAircraftTimeToCollision_array_slice *_TEAircraftTimeToCollision_array_dup (const _TEAircraftTimeToCollision_array_slice* from);

      struct _TEAircraftTimeToCollision_array_uniq_ {};
      typedef DDS_DCPS_FArray_var< _TEAircraftTimeToCollision_array, _TEAircraftTimeToCollision_array_slice, struct _TEAircraftTimeToCollision_array_uniq_> _TEAircraftTimeToCollision_array_var;
      typedef DDS_DCPS_Array_forany< _TEAircraftTimeToCollision_array, _TEAircraftTimeToCollision_array_slice, struct _TEAircraftTimeToCollision_array_uniq_> _TEAircraftTimeToCollision_array_forany;
      DDS::Long ID;
      _TEAircraftExists_array TEAircraftExists;
      _TEAircraftName_array TEAircraftName;
      _TEAircraftVelocity_array TEAircraftVelocity;
      _TEAircraftLatitude_array TEAircraftLatitude;
      _TEAircraftLongitude_array TEAircraftLongitude;
      _TEAircraftAltitude_array TEAircraftAltitude;
      _TEAircraftHeading_array TEAircraftHeading;
      _TEAircraftPitchAngle_array TEAircraftPitchAngle;
      _TEAircraftRollAngle_array TEAircraftRollAngle;
      _TEAircraftRateOfClimb_array TEAircraftRateOfClimb;
      _TEAircraftOnCollissionCourse_array TEAircraftOnCollissionCourse;
      _TEAircraftTimeToCollision_array TEAircraftTimeToCollision;
   };

   typedef DDS_DCPSStruct_var < TacticalAircraftsData> TacticalAircraftsData_var;
   typedef DDS_DCPSStruct_out < TacticalAircraftsData> TacticalAircraftsData_out;
}
template <>
TacticalAircrafts::TacticalAircraftsData::_TEAircraftExists_array_slice* DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftExists_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftExists_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftExists_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftExists_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftExists_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftExists_array_uniq_>::copy (TacticalAircrafts::TacticalAircraftsData::_TEAircraftExists_array_slice *to, const TacticalAircrafts::TacticalAircraftsData::_TEAircraftExists_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftExists_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftExists_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftExists_array_uniq_>::free (TacticalAircrafts::TacticalAircraftsData::_TEAircraftExists_array_slice *ptr);
template <>
TacticalAircrafts::TacticalAircraftsData::_TEAircraftName_array_slice* DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftName_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftName_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftName_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftName_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftName_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftName_array_uniq_>::copy (TacticalAircrafts::TacticalAircraftsData::_TEAircraftName_array_slice *to, const TacticalAircrafts::TacticalAircraftsData::_TEAircraftName_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftName_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftName_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftName_array_uniq_>::free (TacticalAircrafts::TacticalAircraftsData::_TEAircraftName_array_slice *ptr);
template <>
TacticalAircrafts::TacticalAircraftsData::_TEAircraftVelocity_array_slice* DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftVelocity_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftVelocity_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftVelocity_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftVelocity_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftVelocity_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftVelocity_array_uniq_>::copy (TacticalAircrafts::TacticalAircraftsData::_TEAircraftVelocity_array_slice *to, const TacticalAircrafts::TacticalAircraftsData::_TEAircraftVelocity_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftVelocity_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftVelocity_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftVelocity_array_uniq_>::free (TacticalAircrafts::TacticalAircraftsData::_TEAircraftVelocity_array_slice *ptr);
template <>
TacticalAircrafts::TacticalAircraftsData::_TEAircraftLatitude_array_slice* DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftLatitude_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftLatitude_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftLatitude_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftLatitude_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftLatitude_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftLatitude_array_uniq_>::copy (TacticalAircrafts::TacticalAircraftsData::_TEAircraftLatitude_array_slice *to, const TacticalAircrafts::TacticalAircraftsData::_TEAircraftLatitude_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftLatitude_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftLatitude_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftLatitude_array_uniq_>::free (TacticalAircrafts::TacticalAircraftsData::_TEAircraftLatitude_array_slice *ptr);
template <>
TacticalAircrafts::TacticalAircraftsData::_TEAircraftLongitude_array_slice* DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftLongitude_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftLongitude_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftLongitude_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftLongitude_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftLongitude_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftLongitude_array_uniq_>::copy (TacticalAircrafts::TacticalAircraftsData::_TEAircraftLongitude_array_slice *to, const TacticalAircrafts::TacticalAircraftsData::_TEAircraftLongitude_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftLongitude_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftLongitude_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftLongitude_array_uniq_>::free (TacticalAircrafts::TacticalAircraftsData::_TEAircraftLongitude_array_slice *ptr);
template <>
TacticalAircrafts::TacticalAircraftsData::_TEAircraftAltitude_array_slice* DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftAltitude_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftAltitude_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftAltitude_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftAltitude_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftAltitude_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftAltitude_array_uniq_>::copy (TacticalAircrafts::TacticalAircraftsData::_TEAircraftAltitude_array_slice *to, const TacticalAircrafts::TacticalAircraftsData::_TEAircraftAltitude_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftAltitude_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftAltitude_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftAltitude_array_uniq_>::free (TacticalAircrafts::TacticalAircraftsData::_TEAircraftAltitude_array_slice *ptr);
template <>
TacticalAircrafts::TacticalAircraftsData::_TEAircraftHeading_array_slice* DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftHeading_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftHeading_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftHeading_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftHeading_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftHeading_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftHeading_array_uniq_>::copy (TacticalAircrafts::TacticalAircraftsData::_TEAircraftHeading_array_slice *to, const TacticalAircrafts::TacticalAircraftsData::_TEAircraftHeading_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftHeading_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftHeading_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftHeading_array_uniq_>::free (TacticalAircrafts::TacticalAircraftsData::_TEAircraftHeading_array_slice *ptr);
template <>
TacticalAircrafts::TacticalAircraftsData::_TEAircraftPitchAngle_array_slice* DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftPitchAngle_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftPitchAngle_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftPitchAngle_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftPitchAngle_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftPitchAngle_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftPitchAngle_array_uniq_>::copy (TacticalAircrafts::TacticalAircraftsData::_TEAircraftPitchAngle_array_slice *to, const TacticalAircrafts::TacticalAircraftsData::_TEAircraftPitchAngle_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftPitchAngle_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftPitchAngle_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftPitchAngle_array_uniq_>::free (TacticalAircrafts::TacticalAircraftsData::_TEAircraftPitchAngle_array_slice *ptr);
template <>
TacticalAircrafts::TacticalAircraftsData::_TEAircraftRollAngle_array_slice* DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftRollAngle_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftRollAngle_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftRollAngle_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftRollAngle_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftRollAngle_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftRollAngle_array_uniq_>::copy (TacticalAircrafts::TacticalAircraftsData::_TEAircraftRollAngle_array_slice *to, const TacticalAircrafts::TacticalAircraftsData::_TEAircraftRollAngle_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftRollAngle_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftRollAngle_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftRollAngle_array_uniq_>::free (TacticalAircrafts::TacticalAircraftsData::_TEAircraftRollAngle_array_slice *ptr);
template <>
TacticalAircrafts::TacticalAircraftsData::_TEAircraftRateOfClimb_array_slice* DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftRateOfClimb_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftRateOfClimb_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftRateOfClimb_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftRateOfClimb_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftRateOfClimb_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftRateOfClimb_array_uniq_>::copy (TacticalAircrafts::TacticalAircraftsData::_TEAircraftRateOfClimb_array_slice *to, const TacticalAircrafts::TacticalAircraftsData::_TEAircraftRateOfClimb_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftRateOfClimb_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftRateOfClimb_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftRateOfClimb_array_uniq_>::free (TacticalAircrafts::TacticalAircraftsData::_TEAircraftRateOfClimb_array_slice *ptr);
template <>
TacticalAircrafts::TacticalAircraftsData::_TEAircraftOnCollissionCourse_array_slice* DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftOnCollissionCourse_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftOnCollissionCourse_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftOnCollissionCourse_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftOnCollissionCourse_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftOnCollissionCourse_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftOnCollissionCourse_array_uniq_>::copy (TacticalAircrafts::TacticalAircraftsData::_TEAircraftOnCollissionCourse_array_slice *to, const TacticalAircrafts::TacticalAircraftsData::_TEAircraftOnCollissionCourse_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftOnCollissionCourse_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftOnCollissionCourse_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftOnCollissionCourse_array_uniq_>::free (TacticalAircrafts::TacticalAircraftsData::_TEAircraftOnCollissionCourse_array_slice *ptr);
template <>
TacticalAircrafts::TacticalAircraftsData::_TEAircraftTimeToCollision_array_slice* DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftTimeToCollision_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftTimeToCollision_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftTimeToCollision_array_uniq_>::alloc ();
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftTimeToCollision_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftTimeToCollision_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftTimeToCollision_array_uniq_>::copy (TacticalAircrafts::TacticalAircraftsData::_TEAircraftTimeToCollision_array_slice *to, const TacticalAircrafts::TacticalAircraftsData::_TEAircraftTimeToCollision_array_slice* from);
template <>
void DDS_DCPS_ArrayHelper < TacticalAircrafts::TacticalAircraftsData::_TEAircraftTimeToCollision_array, TacticalAircrafts::TacticalAircraftsData::_TEAircraftTimeToCollision_array_slice, TacticalAircrafts::TacticalAircraftsData::_TEAircraftTimeToCollision_array_uniq_>::free (TacticalAircrafts::TacticalAircraftsData::_TEAircraftTimeToCollision_array_slice *ptr);




#endif 
